/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.joshuakegley.panels;
import com.joshuakegley.hcitranslation.MainDriver;
import com.translatorService.Language;
import com.joshuakegley.hcitranslation.Settings;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
/**
 *
 * @author Josh
 */
public class LanguageInterface extends JPanel {
    Language languages = new Language();
    /**
     * Creates new form languageInterface
     */
    public String selectedLangLabel = null;
    public String selectedLangCode = null;
    public String user;
    
    public LanguageInterface(){
        super();
        initComponents();
    }
    
    public LanguageInterface(String title) {
        super();
        initComponents();
        this.userLabel.setText("User" + " " + title + ":");
        user = title; 
    }
    
    private JRadioButton getSelectedRadioButton(ButtonGroup buttonGroup) {

        Enumeration<AbstractButton> abstractButtons = buttonGroup.getElements();
        JRadioButton radioButton = null;

        while (abstractButtons.hasMoreElements()) {
            radioButton = (JRadioButton) abstractButtons.nextElement();
            if (radioButton.isSelected()) {
                break;
            }
        }
        return radioButton;
    }
    
    public void setPanelInvisible(){
        this.setVisible(false);
    }
    
    public void setPanelVisible(){
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectLang = new javax.swing.ButtonGroup();
        chooseText = new javax.swing.JLabel();
        arabFlag = new javax.swing.JLabel();
        arabicRadio = new javax.swing.JRadioButton();
        bengaliFlag = new javax.swing.JLabel();
        bengaliRadio = new javax.swing.JRadioButton();
        frenchRadio = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        englishRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        hindiRadio = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        mandarinRadio = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        russianRadio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        portRadio = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        indonRadio = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        spanishRadio = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        dropdownLang = new javax.swing.JComboBox();
        orText = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();

        chooseText.setFont(new java.awt.Font("Quicksand", 0, 36)); // NOI18N
        chooseText.setText("Choose Language:");

        arabFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Saudi Arabia.png"))); // NOI18N

        selectLang.add(arabicRadio);
        arabicRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        arabicRadio.setText("Arabic");
        arabicRadio.setName("3"); // NOI18N
        arabicRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });
        arabicRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arabicRadioActionPerformed(evt);
            }
        });

        bengaliFlag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Bangladesh.png"))); // NOI18N

        selectLang.add(bengaliRadio);
        bengaliRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        bengaliRadio.setText("Bengali");
        bengaliRadio.setName("6"); // NOI18N
        bengaliRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        selectLang.add(frenchRadio);
        frenchRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        frenchRadio.setText("French");
        frenchRadio.setName("21"); // NOI18N
        frenchRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/United States of America.png"))); // NOI18N

        selectLang.add(englishRadio);
        englishRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        englishRadio.setSelected(true);
        englishRadio.setText("English");
        englishRadio.setName("16"); // NOI18N
        englishRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/France.png"))); // NOI18N

        selectLang.add(hindiRadio);
        hindiRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        hindiRadio.setText("Hindustani");
        hindiRadio.setName("29"); // NOI18N
        hindiRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/China.png"))); // NOI18N

        selectLang.add(mandarinRadio);
        mandarinRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        mandarinRadio.setText("Mandarin");
        mandarinRadio.setName("10"); // NOI18N
        mandarinRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/India.png"))); // NOI18N

        selectLang.add(russianRadio);
        russianRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        russianRadio.setText("Russian");
        russianRadio.setName("49"); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Portugal.png"))); // NOI18N

        selectLang.add(portRadio);
        portRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        portRadio.setText("Portuguese");
        portRadio.setName("47"); // NOI18N
        portRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Russian Federation.png"))); // NOI18N

        selectLang.add(indonRadio);
        indonRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        indonRadio.setText("Maly-Indonesian");
        indonRadio.setName("32"); // NOI18N
        indonRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Mexico.png"))); // NOI18N

        selectLang.add(spanishRadio);
        spanishRadio.setFont(new java.awt.Font("Quicksand", 2, 14)); // NOI18N
        spanishRadio.setText("Spanish");
        spanishRadio.setName("53"); // NOI18N
        spanishRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arabicRadioItemStateChanged(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flags/Indonesia.png"))); // NOI18N

        selectButton.setText("Select");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        dropdownLang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dropdownLang.setModel(new javax.swing.DefaultComboBoxModel(languages.lang));
        dropdownLang.setToolTipText("");
        dropdownLang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dropdownLangItemStateChanged(evt);
            }
        });

        orText.setFont(new java.awt.Font("Quicksand", 2, 36)); // NOI18N
        orText.setText("Or...");

        userLabel.setFont(new java.awt.Font("Quicksand", 2, 24)); // NOI18N
        userLabel.setText("-------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chooseText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frenchRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(englishRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bengaliFlag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bengaliRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(arabFlag)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arabicRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hindiRadio)))
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mandarinRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(russianRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spanishRadio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indonRadio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(orText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dropdownLang, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arabicRadio)
                            .addComponent(arabFlag))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bengaliRadio)
                            .addComponent(bengaliFlag)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(indonRadio)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(mandarinRadio))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portRadio)
                    .addComponent(jLabel8)
                    .addComponent(englishRadio)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frenchRadio)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hindiRadio)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(russianRadio)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spanishRadio)
                            .addComponent(jLabel10))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropdownLang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orText)
                        .addGap(47, 47, 47))))
        );

        dropdownLang.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    /**/
    
    
    private void dropdownLangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dropdownLangItemStateChanged
        selectLang.clearSelection();
    }//GEN-LAST:event_dropdownLangItemStateChanged

    private void arabicRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_arabicRadioItemStateChanged
        dropdownLang.setSelectedIndex(0);
    }//GEN-LAST:event_arabicRadioItemStateChanged

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        if(dropdownLang.getSelectedIndex() != 0){
            selectedLangCode = languages.langCode[dropdownLang.getSelectedIndex()];
            selectedLangLabel = languages.lang[dropdownLang.getSelectedIndex()];

        }else if(getSelectedRadioButton(selectLang) != null){
            selectedLangCode = languages.langCode[Integer.parseInt(getSelectedRadioButton(selectLang).getName())];
            selectedLangLabel = languages.lang[Integer.parseInt(getSelectedRadioButton(selectLang).getName())];
        }else{
        }
        if(user == "One"){
            Settings.setLang1(selectedLangLabel, selectedLangCode);
            TranslateInterface.setLang1(selectedLangLabel, selectedLangCode);
            setVisible(false);
        }else{
            Settings.setLang2(selectedLangLabel, selectedLangCode);
            TranslateInterface.setLang2(selectedLangLabel, selectedLangCode);
            setVisible(false);
        }
    }//GEN-LAST:event_selectButtonActionPerformed

    private void arabicRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arabicRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arabicRadioActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arabFlag;
    private javax.swing.JRadioButton arabicRadio;
    private javax.swing.JLabel bengaliFlag;
    private javax.swing.JRadioButton bengaliRadio;
    private javax.swing.JLabel chooseText;
    public javax.swing.JComboBox dropdownLang;
    private javax.swing.JRadioButton englishRadio;
    private javax.swing.JRadioButton frenchRadio;
    private javax.swing.JRadioButton hindiRadio;
    private javax.swing.JRadioButton indonRadio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton mandarinRadio;
    private javax.swing.JLabel orText;
    private javax.swing.JRadioButton portRadio;
    private javax.swing.JRadioButton russianRadio;
    private javax.swing.JButton selectButton;
    private javax.swing.ButtonGroup selectLang;
    private javax.swing.JRadioButton spanishRadio;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables

}
